{% set name = "holopy" %}
{% set repo = "manoharan-lab" %}
{% set version = "3.4.0" %}
{% set sha256 = "efac38df58a9925e9cfaec11e895c0ac22a721e1162d44e1e26be56bb02d0f43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}-{{ version }}.tar.gz
  url: https://github.com/{{ repo }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py2k]
  script: "{{ PYTHON }} setup.py install"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}  # [not win]
  host:
    - python
    - pip
    - {{ pin_compatible('numpy') }}
    - setuptools
    - m2w64-toolchain  # [win]
    - nose
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pyyaml
    - pillow
    - h5py
    - xarray
    - h5netcdf
    - pandas

test:
  imports:
    - holopy
    - holopy.scattering.theory.mie_f.mieangfuncs
    - holopy.scattering.theory.mie_f.scsmfo_min
    - holopy.scattering.theory.tmatrix_f.S

about:
  home: http://manoharan.seas.harvard.edu/holopy
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Holopy is a python based tool for working with digital holograms and light scattering'

  description: |
    HoloPy is a software package for computational light scattering and digital holography.
    It has tools for managing data and metadata, doing reconstructions, computing light scattering
    from micron scale particles or clusters of such particles, and fitting scattering models to
    digital holograms to measure particle parameters. HoloPy is free and open source software (GPL v3).
  doc_url: http://holopy.readthedocs.io/
  dev_url: https://github.com/manoharan-lab/holopy

extra:
  recipe-maintainers:
    - ralex0
    - barkls
    - vnmanoharan
