{% set name = "HoloPy" %}
{% set version = "3.2.1" %}
{% set sha256 = "6994fb24ef20dabdb016ee0e624e474507f5abd48c6135837b09ccccc5b6ee77" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}-{{ version }}.tar.gz
  url: https://github.com/manoharan-lab/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [py2k or win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - python
    - pip
    - {{ pin_compatible('numpy') }}
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy < 1.2.0
    - pyyaml
    - pillow
    - h5py
    - emcee
    - matplotlib
    - xarray >=0.10.0
    - h5netcdf
    
test:
  imports:
    - holopy

about:
  home: http://manoharan.seas.harvard.edu/holopy
  license: GPL v3
  license_file: COPYING
  summary: 'Holopy is a python based tool for working with digital holograms and light scattering'

  description: |
    HoloPy is a software package for computational light scattering and digital holography. 
    It has tools for managing data and metadata, doing reconstructions, computing light scattering
    from micron scale particles or clusters of such particles, and fitting scattering models to
    digital holograms to measure particle parameters. HoloPy is free and open source software (GPL v3).
  doc_url: http://holopy.readthedocs.io/
  dev_url: https://github.com/manoharan-lab/holopy

extra:
  recipe-maintainers:
    - barkls
    - vnmanoharan
